### PR TITLE
Back to author

### PR DESCRIPTION
**Pull request by tvladyslav**
Merge new tests and OCRA implementation to original lib

### CODE REVIEW

**Comment by tvladyslav** [comment]
@avacariu so as I told, adapt readme to the new reality and publish it, then I'll abandon my fork.
By the way, ieee754 looks to be fixed, so ramp must work and you'll need to remove that workaround in ocra_debug function.

**Comment by avacariu** [comment]
Thanks for the PR! I've published the new version to crates.io.

**Comment by newpavlov** [comment]
Sorry for the late comment, but you've published version 0.10.1 (crypto-universe bumped it up to 0.9 after fork), while the last version was 0.1.4. I think it will be better to yank it and publish 0.2.0 instead.

**Comment by tvladyslav** [comment]
Decreasing version will introduce chaos and no benefits. Skipped a few numbers is not a problem. As for me, it is better to keep the version as it is. Just IMHO.

**Comment by avacariu** [comment]
This PR went up to 0.10.0, and I just bumped it up to 0.10.1 when I renamed it back to `oath`. I think it'd be confusing to have a bunch of commits that increase version number, and then 1 that decreases it, so I'll leave it as it is and we can be more careful with version numbers in the future.

**Pull request merged**
